use_frameworks!

target 'CDFlipView_Example' do
  pod 'CDFlipView', :path => '../'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
end

target 'CDFlipView_Tests' do
  pod 'CDFlipView', :path => '../'
end
